### ISSUE TITLE
Prefer plain YAML in Salt configs

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#130]
The Salt configs used to manage the multi-VM setup are currently rather inscrutable. The initial work on Salt in this repo was assembled by referencing the Qubes-provided configs in `dom0:/srv/salt/qubes`. They make use of a number of helper functions that evidently have proved convenient for the Qubes developers, but may inhibit maintainability on our end.

By way of example:

```
{%- from "qvm/template.jinja" import load -%}

{% load_yaml as defaults -%}
name:         sd-journalist
present:
  - template: whonix-ws-14
  - label:    blue
prefs:
  - netvm:    sd-whonix
require:
  - pkg:      qubes-template-whonix-ws-14
  - qvm:      sd-whonix
{%- endload %}

{{ load(defaults) }}
```

Can be written in plain YAML as:

```
sd-journalist:
  qvm.vm:
    - name: sd-journalist
    - present:
        - template: whonix-ws-14
        - label: blue
    - prefs:
        - netvm: sd-whonix
  require:
    - pkg: qubes-template-whonix-ws-14
    - qvm: sd-whonix
```

The indirection via Jinja2 templates doesn't enable terser configs; worse, it hurts readability.

See reference and examples in the [qubes-mgt-salt-dom0-qvm ](https://github.com/QubesOS/qubes-mgmt-salt-dom0-qvm#qvm-vm) repo. Simplifying the Salt configs by using plain YAML will also permit us to lint (and validate) the YAML as described in #56, which we cannot do when the files contain Jinja2 commands.
