### ISSUE TITLE
Whonix update error

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-workstation#184]
I am seeing this error time to time (from last night). 

```
----------
          ID: sd-journalist
    Function: qvm.vm
      Result: True
     Comment: ====== ['present'] ======
              [SKIP] A VM with the name 'sd-journalist' already exists.
              
              ====== ['prefs'] ======
              [SKIP] netvm              : sd-whonix
     Started: 23:41:50.439336
    Duration: 574.128 ms
     Changes:   
----------
          ID: /etc/qubes-rpc/policy/sd-process.Feedback
    Function: file.managed
      Result: True
     Comment: File /etc/qubes-rpc/policy/sd-process.Feedback is in the correct state
     Started: 23:41:51.013894
    Duration: 4.672 ms
     Changes:   
----------
          ID: install python-qt4 and python-futures
    Function: cmd.run
        Name: qvm-run -a whonix-ws-14 'sudo apt-get update && sudo apt-get install -qq python-futures python-qt4'
      Result: False
     Comment: Command "qvm-run -a whonix-ws-14 'sudo apt-get update && sudo apt-get install -qq python-futures python-qt4'" run
     Started: 23:41:51.018721
    Duration: 6088.569 ms
     Changes:   
              ----------
```

Just documenting it here.
