### ISSUE TITLE
Create menu entry for securedrop-client

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#198]
As we integrate the `securedrop-client` package for use on the workstation (#179), it's become clear that we need a corresponding desktop file to populate the Qubes menu, so users have a way to start the application via GUI interaction. (At present, one must run `qvm-run sd-svs securedrop-client` in dom0, which is hardly ideal.)

It'd be grand to have _only_ the securedrop-client in the menu entry for sd-svs, rather than the default smogasbord of Debian apps. There's example logic we can crib in `/srv/formulas/base/virtual-machines-formula/qvm/default-dispvm.sls`:

```
echo -e 'firefox.desktop\nxterm.desktop' | qvm-appmenus --set-whitelist=- --update fedora-28-dvm:
  cmd.run:
    - runas: {{ gui_user }}
    - requires:
      - qvm: fedora-28-dvm
```

We can do the same for the securedrop-client app, but we'll need a desktop file first. It should probably be added to client repo itself as a file in the MANIFEST, then we can add a corresponding Salt line here to update the Qubes menu.
