### ISSUE TITLE
Templates fail to update due to buster "oldstable" status

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#721]
During a clean install in support of #717, I encountered this failure:

```
  ----------
            ID: update
      Function: pkg.uptodate
        Result: False
       Comment: E: Repository 'https://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
                E: Repository 'https://deb.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
       Started: 09:47:31.090662
      Duration: 5025.744 ms
       Changes:   
  ----------
```

That same error will bite us on the updater runs, blocking upgrades until resolved. 

There's an option we can use to resolve: `apt-get --allow-releaseinfo-change update` but we'll need to make sure we can run that prior to any other apt commands.
