### ISSUE TITLE
`sdw-admin --apply` does not apply all required Salt states

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#825]
## Summary

`sdw-admin --apply` appears to be applying only the Salt states targeting `dom0` successfully. Other Salt states don't do anything, printing only the output `test.succeed_without_changes` and the result `True`.

## Steps to reproduce

1. Uninstall your SecureDrop Workstation code (e.g., `sdw-admin --uninstall` or `make clean`)
2. Reinstall the RPM and reprovision (e.g., install RPM and run `sdw-admin --apply`)

## Expected behavior

1. The process completes without errors.
2. You have a working SecureDrop Workstation.

## Actual behavior

1. The process completes without errors.
2. VM-specific configuration (e.g., package installation, MIME type provisioning) are not installed.
3. Salt states like `sd-small-bullseye-template` complete with output like this:

```
sd-small-bullseye-template:
  ----------
            ID: topd-always-passes
      Function: test.succeed_without_changes
          Name: foo
        Result: True
       Comment: Success!
       Started: 14:00:35.412466
      Duration: 0.969 ms
       Changes:   
  ```
