### ISSUE TITLE
[4.2] Drop Salt installation of required packages in cloned base template in favour of securedrop-workstation-config

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#977]
Packages required by SDW but not present in `debian-12-minimal` are currently installed via the following Salt stanza in `dom0/sd-base-template-files.sls`. When https://github.com/freedomofpress/securedrop-client/pull/1957 lands, this stanza can be dropped:

```
# TODO: test if this works, if not it may need to be a qvm-run command          
sd-base-template-install-additional-packages:                                   
  pkg.installed:                                                                
    - pkgs:                                                                     
      - qubes-core-agent-passwordless-root                                      
      - rsyslog                                                                 
      - mailcap                                                                 
      - apparmor                                                                
      - apparmor-utils  
``` 

(This will be one less Salt thing but the actual package install will still take place, so complexity reduction, but minimal time reduction.)
